# Generated by Django 5.2.7 on 2025-11-11 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('pais_origem', models.CharField(max_length=100)),
                ('idioma_nativo', models.CharField(max_length=50)),
                ('status_refugio', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('RECONHECIDO', 'Reconhecido'), ('NEGADO', 'Negado'), ('REGULARIZACAO', 'Em Regularização'), ('OUTRO', 'Outro')], default='SOLICITANTE', max_length=15)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_endereco', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('idiomas_falados', models.TextField(help_text='Lista de idiomas separados por vírgula')),
                ('habilidades_oferecidas', models.TextField(help_text='Lista de habilidades separadas por vírgula')),
                ('disponibilidade', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
