# Generated by Django 5.2.7 on 2025-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugiado',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='cep',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='complemento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='estado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='logradouro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='refugiado',
            name='numero_endereco',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='disponibilidade',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='habilidades_oferecidas',
            field=models.TextField(default='', help_text='Lista de habilidades separadas por vírgula'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='idiomas_falados',
            field=models.TextField(default='', help_text='Lista de idiomas separados por vírgula'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='localizacao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
