# Generated by Django 5.2.7 on 2025-11-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('habilidade_necessaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status_solicitacao', models.CharField(default='ABERTO', max_length=20)),
                ('refugiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.refugiado')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntarioHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.habilidade')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.voluntario')),
            ],
            options={
                'verbose_name_plural': 'Habilidades Oferecidas (Voluntários)',
                'unique_together': {('voluntario', 'habilidade')},
            },
        ),
    ]
